#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=863264658669
BundleId=com.newbgames.cavebat
ClientId=863264658669-1s6ti3qq3h5ckufkgkmn3i6c1o213t0h.apps.googleusercontent.com

*/

#define kAppID "863264658669"
#define kBundleID "com.newbgames.cavebat"
#define kClientID "863264658669-1s6ti3qq3h5ckufkgkmn3i6c1o213t0h.apps.googleusercontent.com"

#endif


